### PR TITLE
Move benchmarks into separate repo

### PR DESCRIPTION
**Pull request by vsbogd**
things done:
- benchmarks are moved to new repository preserving history
- pattern matcher benchmark is moved to query folder

### CODE REVIEW

**Comment by ngeiswei** [comment]
It looks good to me, @vsbogd, except that the `atomspace` and `query` folders should be under a parent folder `atomspace`, to indicate that they pertain to the atomspace repo, as suggested in https://github.com/opencog/benchmark/blob/master/README.md. That way benchmarks of other repos can be added their too at a later time. I'm not completely sure it is the right way to go, BTW, if you feel otherwise please let us know, that was just my initial suggestion.

**Comment by ngeiswei** [comment]
That's all looks good to me.

Since it's the first meaningful commit on that repo and Linas has worked with that code a lot more than I, I'll wait 24h in case @linas has something to say about it, then I'll merge.

**Comment by vsbogd** [comment]
Couple of comments about things which are not done:
- I didn't test it on win32 and didn't moved cmake rules related to win32 - not sure should it be supported; can CI be used to gurantee that build is successful
- bindlink_profile app built using Profile build type crashes; it is broken in atomspace repository too I didn't fix it for now
Next steps:
- I would like to extract data from profile_bindlink and make it a tool which can load and query .scm data; so one can commit atomspace as Scheme file and use the tool to run a query, make time measurements and profiling if required.

**Comment by ngeiswei** [comment]
Sounds good, @vsbogd. No need of win32 support. Your description of the next steps make sense.

**Pull request merged**
